version: '3.1'

services:
  mongo:
    container_name: "mongo"
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js